import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    color: '#1b2a49',
    marginBottom: 10,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#415a77',
    marginBottom: 20,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  categoryText: {
    fontSize: 14,
    color: '#415a77',
    marginBottom: 6,
    fontWeight: '600',
  },
  progressText: {
    fontSize: 14,
    color: '#415a77',
    marginBottom: 6,
    fontWeight: '600',
  },
  timerText: {
    fontSize: 14,
    color: '#e63946',
    marginBottom: 14,
    fontWeight: '700',
  },
  questionText: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0d1b2a',
    marginBottom: 20,
  },
  optionButton: {
    borderWidth: 2,
    borderColor: '#d9e2ec',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: '#ffffff',
  },
  optionText: {
    fontSize: 16,
    color: '#1b263b',
    fontWeight: '600',
  },
  optionCorrect: {
    borderColor: '#2a9d8f',
    backgroundColor: '#e6f8f6',
  },
  optionIncorrect: {
    borderColor: '#e63946',
    backgroundColor: '#ffebee',
  },
  optionHidden: {
    borderColor: '#d0d7e2',
    backgroundColor: '#f4f6fa',
    opacity: 0.6,
  },
  primaryButton: {
    backgroundColor: '#1b2a49',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  primaryButtonDisabled: {
    backgroundColor: '#9aa8bb',
  },
  secondaryButton: {
    borderWidth: 2,
    borderColor: '#1b2a49',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  secondaryButtonText: {
    color: '#1b2a49',
    fontSize: 15,
    fontWeight: '700',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  scoreText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0d1b2a',
    marginBottom: 8,
  },
  percentText: {
    fontSize: 20,
    color: '#415a77',
    marginBottom: 10,
    fontWeight: '600',
  },
  highScoreText: {
    fontSize: 16,
    color: '#1b2a49',
    marginBottom: 8,
    fontWeight: '600',
  },
  settingLabel: {
    marginTop: 4,
    marginBottom: 8,
    fontSize: 14,
    color: '#415a77',
    fontWeight: '700',
  },
  inlineOptionsRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  chipButton: {
    borderWidth: 1,
    borderColor: '#b8c5d8',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 6,
  },
  chipButtonActive: {
    backgroundColor: '#1b2a49',
    borderColor: '#1b2a49',
  },
  chipButtonText: {
    color: '#1b2a49',
    fontWeight: '700',
  },
  chipButtonTextActive: {
    color: '#ffffff',
  },
  dailyChallengeButton: {
    borderRadius: 12,
    backgroundColor: '#ffb703',
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 4,
  },
  dailyChallengeText: {
    color: '#2b2d42',
    fontWeight: '800',
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#dde5f0',
    marginBottom: 10,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#2a9d8f',
  },
  quizMetaText: {
    fontSize: 13,
    color: '#415a77',
    marginBottom: 4,
    fontWeight: '600',
  },
  inlineActionButton: {
    flex: 1,
    minWidth: 130,
    paddingHorizontal: 8,
  },
  correctFeedback: {
    color: '#2a9d8f',
    fontWeight: '700',
    marginBottom: 8,
  },
  wrongFeedback: {
    color: '#e63946',
    fontWeight: '700',
    marginBottom: 8,
  },
  challengeBadge: {
    alignSelf: 'flex-start',
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: '#ffe8a3',
    color: '#6b4f00',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontWeight: '700',
  },
  performanceText: {
    fontSize: 18,
    color: '#1b2a49',
    fontWeight: '800',
    marginBottom: 10,
  },
});

export default styles;
